### ISSUE TITLE
Get elements of vector as Float/Double/Integer

### ISSUE THREAD

**Issue by johanneskool** [sleexyz/hylogen#80]
Make it possible to get the n-th elementh of a vector as a Float/Integer/Double. Right now it's impossible to do calculations with, for example, the x-coordinate of a pixel.

For example:
x = toFloat (x_ uvN)
y = toFloat (y_ uvN)
complex_coordinate = x :+ y

**Comment by sleexyz** [comment]
When you say "Float" or "Double" or "Integer", are you talking about the Haskell datatypes?

If so, conversion from any of the Hylogen datatypes (`Vec1`, `Vec2`, etc) to any concrete Haskell datatype is impossible, since the Haskell part of Hylogen only generates a static shader; none of the values are known at "runtime with respect to Haskell".

In Hylogen you essentially specify a computation graph, and then that computation graph gets compiled into a shader. That shader specifies a program that runs later, completely independently of Haskell.

---

If your goal is to make use of Prelude's `Data.Complex`, then unfortunately you're out of luck, unless they make an appropriately typeclassed version of `Complex` (much in the way that `Num` and `Floating` are typeclassed, and are implemented by [some Hylogen datatypes](https://github.com/sleexyz/hylogen/blob/master/hylogen/src/Hylogen/Types/Vec.hs)).
